export const seedCategories = [
  {
    id: 'clothes',
    name: 'Clothes',
    image:
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'shoes',
    name: 'Shoes',
    image:
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'perfumes',
    name: 'Perfumes',
    image:
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'bags',
    name: 'Bags',
    image:
      'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'electronics',
    name: 'Electronics',
    image:
      'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'kitchen',
    name: 'Kitchen',
    image:
      'https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'gifts',
    name: 'Gifts',
    image:
      'https://images.unsplash.com/photo-1513201099705-a9746e1e201f?auto=format&fit=crop&w=700&q=80',
  },
  {
    id: 'beauty',
    name: 'Beauty',
    image:
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=700&q=80',
  },
];

export const seedBanners = [
  {
    id: 'banner-one',
    image:
      'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?auto=format&fit=crop&w=1600&q=80',
    cta: '/shop?collection=new-arrivals',
    alt: 'New arrivals campaign',
  },
  {
    id: 'banner-two',
    image:
      'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1600&q=80',
    cta: '/shop?collection=accessories',
    alt: 'Accessories campaign',
  },
  {
    id: 'banner-three',
    image:
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=80',
    cta: '/shop?collection=tech',
    alt: 'Tech campaign',
  },
  {
    id: 'banner-four',
    image:
      'https://images.unsplash.com/photo-1607083206968-13611e3d76db?auto=format&fit=crop&w=1600&q=80',
    cta: '/shop?collection=deals',
    alt: 'Deals campaign',
  },
  {
    id: 'banner-five',
    image:
      'https://images.unsplash.com/photo-1445205170230-053f21742ee8?auto=format&fit=crop&w=1600&q=80',
    cta: '/shop',
    alt: 'Mall campaign',
  },
];

export const seedProducts = [
  {
    id: 'silk-midi-dress',
    name: 'Silk Midi Dress',
    image:
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=80',
    price: 89000,
    originalPrice: 124000,
    rating: 4.9,
    discount: 28,
    isFeatured: true,
    isFlashSale: true,
    category: 'Clothes',
    brand: 'Maison PS',
    colors: ['Purple', 'Black'],
    sizes: ['S', 'M', 'L'],
    availability: 'In Stock',
    isNew: true,
    popularity: 98,
    sales: 420,
    stock: 18,
    description: 'A refined everyday essential selected for quality, finish, and lasting appeal.',
    specifications: ['Premium finish', 'Carefully sourced materials', 'Gift-ready packaging'],
  },
  {
    id: 'leather-shopper',
    name: 'Leather Shopper Bag',
    image:
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    price: 76000,
    originalPrice: 94000,
    rating: 4.8,
    discount: 19,
    isFeatured: true,
    isFlashSale: true,
    category: 'Bags',
    brand: 'Velour',
    colors: ['Tan', 'Black'],
    sizes: ['One Size'],
    availability: 'In Stock',
    isNew: false,
    popularity: 92,
    sales: 360,
    stock: 12,
    description: 'Structured leather shopper with room for workdays and weekends.',
    specifications: ['Full-grain leather', 'Interior pocket', 'Gift-ready packaging'],
  },
  {
    id: 'signature-sneakers',
    name: 'Signature Sneakers',
    image:
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
    price: 68000,
    originalPrice: 85000,
    rating: 4.7,
    discount: 20,
    isFeatured: true,
    isFlashSale: true,
    category: 'Shoes',
    brand: 'Sable',
    colors: ['White', 'Gold'],
    sizes: ['39', '40', '41', '42'],
    availability: 'In Stock',
    isNew: true,
    popularity: 89,
    sales: 310,
    stock: 24,
    description: 'Clean court sneakers with a gold-trimmed finish.',
    specifications: ['Cushioned insole', 'Leather upper', 'Quality checked before dispatch'],
  },
  {
    id: 'noir-perfume',
    name: 'Noir Eau de Parfum',
    image:
      'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=80',
    price: 52000,
    originalPrice: 65000,
    rating: 4.9,
    discount: 20,
    isFeatured: true,
    isFlashSale: true,
    category: 'Perfumes',
    brand: 'Noir Haus',
    colors: ['Black'],
    sizes: ['50ml', '100ml'],
    availability: 'Low Stock',
    isNew: false,
    popularity: 95,
    sales: 390,
    stock: 7,
    description: 'A dark floral scent with amber and cedar.',
    specifications: ['Long-lasting', 'Gift-ready packaging', 'Made for evening wear'],
  },
  {
    id: 'wireless-headphones',
    name: 'Studio Wireless Headphones',
    image:
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    price: 118000,
    originalPrice: 142000,
    rating: 4.8,
    discount: 17,
    isFeatured: true,
    isFlashSale: true,
    category: 'Electronics',
    brand: 'LuxeLab',
    colors: ['Black', 'Silver'],
    sizes: ['One Size'],
    availability: 'In Stock',
    isNew: true,
    popularity: 91,
    sales: 288,
    stock: 15,
    description: 'Studio-grade wireless headphones with a quiet commute in mind.',
    specifications: ['30-hour battery', 'Active noise cancelling', 'USB-C charging'],
  },
  {
    id: 'gold-watch',
    name: 'Classic Gold Watch',
    image:
      'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80',
    price: 98000,
    originalPrice: 0,
    rating: 4.9,
    discount: 0,
    isFeatured: true,
    isFlashSale: false,
    category: 'Accessories',
    brand: 'Aurelia',
    colors: ['Gold'],
    sizes: ['One Size'],
    availability: 'In Stock',
    isNew: false,
    popularity: 87,
    sales: 244,
    stock: 9,
    description: 'A classic gold watch with a slim profile.',
    specifications: ['Stainless steel', 'Water resistant', 'Gift-ready packaging'],
  },
  {
    id: 'ceramic-dinner-set',
    name: 'Ceramic Dinner Set',
    image:
      'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=800&q=80',
    price: 43000,
    originalPrice: 0,
    rating: 4.6,
    discount: 0,
    isFeatured: true,
    isFlashSale: false,
    category: 'Kitchen',
    brand: 'Maison PS',
    colors: ['White'],
    sizes: ['12 Piece'],
    availability: 'In Stock',
    isNew: false,
    popularity: 80,
    sales: 205,
    stock: 20,
    description: 'A 12-piece ceramic set for everyday hosting.',
    specifications: ['Microwave safe', 'Dishwasher safe', 'Quality checked before dispatch'],
  },
  {
    id: 'beauty-kit',
    name: 'Glow Beauty Kit',
    image:
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=800&q=80',
    price: 36000,
    originalPrice: 0,
    rating: 4.8,
    discount: 0,
    isFeatured: true,
    isFlashSale: false,
    category: 'Beauty',
    brand: 'Aurelia',
    colors: ['Pink', 'Gold'],
    sizes: ['Full Kit'],
    availability: 'In Stock',
    isNew: true,
    popularity: 86,
    sales: 275,
    stock: 22,
    description: 'A glow kit with everyday essentials for skin and colour.',
    specifications: ['Cruelty free', 'Travel pouch included', 'Gift-ready packaging'],
  },
];

export const seedCoupons = [{ code: 'PSGOLD', percent: 10, active: true }];
